# Generated by Django 4.2.16 on 2024-11-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='vusualizacoes',
            field=models.IntegerField(default=0),
        ),
    ]
