# Generated by Django 4.2.16 on 2024-11-09 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_alter_filme_vusualizacoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='vusualizacoes',
            new_name='visualizacoes',
        ),
    ]
